### ISSUE TITLE
(Possibly) Outdated Examples

### ISSUE THREAD

**Issue by RickCarlino** [mattn/mruby-thread#58]
Hi,

I was trying out some of the examples and noticed that two of them may be out of date:

* `example/data.rb`:   ArgumentError: undefined class/module MyContainer
* `example/simple.rb`: "[v should be 'bar](https://github.com/mattn/mruby-thread/blob/master/example/simple.rb#L12)'", but isn't (it appears that the thread is not mutating the same variable, or is mutating a copy)

My questions are:

 * Is this a local issue, or an outdated example? (If they are out of date, I can submit a PR to clean the files up, please let me know)
 * Is it possible to send data from a child thread back to the parent thread without blocking? Particularly, data from `$stdin`.

**Comment by take-cheeze** [comment]
The examples is outdated.
It needs updates.
Now local variables can't be mutated from other thread since it will cause data race.
Use `Queue` to pass datas.
Passing `IO` object should be supported: https://github.com/mattn/mruby-thread/blob/7a175186b5f7d9ae7b693664788493c4a88227b3/src/mrb_thread.c#L164
Though haven't tested.

Things under test directory should be working: https://github.com/mattn/mruby-thread/tree/master/test
